# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raise Siren PoC
email: bill.hinderman@raise.com
description: > # this means to ignore newlines until "baseurl:"
  Proof of concept for Raise Marketplace fact page system.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: raise
github_username:  billHinderman

# Build settings
markdown: kramdown

prose:
  rooturl: '_pages'
  media: 'media'
  metadata:
    _pages:
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          placeholder: "/buy-bed-bath-beyond-gift-cards"
          value: ""
      - name: "layout"
        field:
          element: "select"
          label: "Page Layout"
          options:
          - name: 'Page'
            value: 'page'
          - name: 'Post'
            value: 'post'
      - name: "brand-slug"
        field:
          element: "text"
          label: "Brand's Name (slug)"
          placeholder: "bed-bath-beyond"
          value: ""
      - name: "brand-name"
        field:
          element: "text"
          label: "Brand's Name (pretty)"
          placeholder: "Bed Bath & Beyond"
          value: ""
      - name: "testimonial-body"
        field:
          element: "textarea"
          label: "Testimonial Body"
          placeholder: "Lorem ipsum dolor sit amet."
          value: ""
      - name: "testimonial-location"
        field:
          element: "text"
          label: "Testimonial Location"
          placeholder: "Chicago, IL"
          value: ""
      - name: "testimonial-headline"
        field:
          element: "text"
          label: "Testimonial Headline"
          placeholder: "An entrepreneur and savvy shopper, see how he uses Raise to make his money worth more."
          value: ""
      - name: "testimonial-name-first"
        field:
          element: "text"
          label: "Testimonial First Name"
          placeholder: "George"
          value: ""
      - name: "testimonial-name-last"
        field:
          element: "text"
          label: "Testimonial Last Name"
          placeholder: "Busoius"
          value: ""
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Buy Bed Bath & Beyond Gift Cards"
          value: ""
